name: 🤖 Build

on:
  workflow_call:
    inputs:
      matrix:
        type: string
        required: true
        description: "The strategy matrix used to build images"

jobs:
  build-slurm:
    name: Slurm
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(inputs.matrix) }}

    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          tags: ghcr.io/better-hpc/slurm-env/${{ matrix.version }}
          outputs: type=docker,dest=/tmp/image.tar
          build-args: SLURM_VERSION=${{ matrix.version }}
          cache-from: type=gha,scope=build-${{ github.ref_name }}-${{ matrix.version }}
          cache-to: type=gha,mode=max,scope=build-${{ github.ref_name }}-${{ matrix.version }}

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: slurm-${{ matrix.version }}
          path: /tmp/image.tar
