name: 🤖 Build

on:
  workflow_call:
    inputs:
      matrix:
        type: string
        required: true
        description: "The strategy matrix used to build images"

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(inputs.matrix) }}

    steps:
      - name: Test
        run:  echo ${{ matrix.version }}
