name: 🎯 Pull Request

on:
  pull_request:

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/Setup.yml

  build:
    name: Build
    needs: [ setup ]
    uses: ./.github/workflows/Build.yml
    with:
      matrix: ${{ needs.setup.outputs.matrix }}

  test:
    name: Test
    needs: [ setup, build ]
    uses: ./.github/workflows/Test.yml
    with:
      matrix: ${{ needs.setup.outputs.matrix }}

  pr-status:
    name: PR Status
    runs-on: ubuntu-latest
    needs: [ test ]
    if: always()

    steps:
      - name: Check PR status
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
