name: 🎯 Pull Request

on:
  pull_request:

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/Setup.yml

  build:
    name: Build
    needs: [ setup ]
    uses: ./.github/workflows/Build.yml
    with:
      matrix: ${{ needs.setup.outputs.matrix }}
