name: A temporary workflow for CI development

on:
  push:

jobs:
  matrix:
    name: Matrix
    uses: ./.github/workflows/Matrix.yml

  build:
    name: Build
    needs: [ matrix ]
    uses: ./.github/workflows/Build.yml
    with:
      matrix: ${{ needs.matrix.outputs.matrix }}
