name: A temporary workflow for CI development

on:
  push:

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/Setup.yml

  build:
    name: Build
    needs: [ setup ]
    uses: ./.github/workflows/Build.yml
    with:
      matrix: ${{ needs.matrix.outputs.matrix }}
